"""Extract the per-model tokenizer data voidcode ships, from the local oh-my-pi install.

Dev-time generator only; never imported by the runtime. It reads two upstream
artifacts on this machine:

1. omp's native addon (``pi_natives.*.node``) — a Rust N-API library with the
   tokenizer vocabularies embedded as zstd-compressed blobs. Each UTOK1 blob is
   the BPE vocabulary for one encoding: ``"UTOK1\\n"`` + ``<u32 LE token count>``
   + N x (``<ULEB128 byte length>`` + raw token bytes). Rank == index.
2. omp's model routing table (``~/.omp/agent/models.db`` table ``model_cache``)
   — each model JSON carries ``"tokenizer": "<name>"``. The models.dev mirror
   that voidsode's catalog is generated from carries NO such field, so this is
   the only source of the model -> encoding identity.

Outputs (both checked in, both regenerated by re-running this script):

- ``src/voidcode/provider/tokenizer_data/<Encoding>.utok1.bz2`` — the shipped
  vocabularies (bz2 is the smallest stdlib codec; ``zstandard`` is dev-only).
- ``src/voidcode/provider/tokenizer_routing.json`` — the model -> encoding map.

Provenance is recorded in the manifest so the licensing terms stay visible.
"""

from __future__ import annotations

import argparse
import bz2
import json
import re
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "src" / "voidcode" / "provider" / "tokenizer_data"
ROUTING_PATH = REPO_ROOT / "src" / "voidcode" / "provider" / "tokenizer_routing.json"

_ZSTD_MAGIC = b"\x28\xb5\x2f\xfd"
_UTOK1_MAGIC = b"UTOK1\n"

#: Blob fingerprint -> omp encoding name. The UTOK1 blobs carry no name, so they
#: are identified by their exact token count, which is stable for a given vocab.
#: The assignment was verified independently by a 6x6 blob x encoding
#: cross-product on letters/marks/digits-only strings (single pretokenizer piece
#: under any candidate splitter, so the count isolates the vocabulary).
_ENC_BY_TOKEN_COUNT: dict[int, str] = {
    199_998: "O200kBase",
    100_256: "Cl100kBase",
    154_820: "Glm5",
    248_044: "Qwen3",
    163_584: "KimiK2",
    128_000: "DeepSeekV3",
}

#: Per-encoding provenance and licence, recorded so the redistribution terms
#: are visible in the shipped artifact rather than implicit in this script.
#: Two distinct cases:
#:
#: * ``Cl100kBase``/``O200kBase`` are byte-identical, rank for rank, to
#:   tiktoken's own published vocabularies (MIT, upstream OpenAI). Redistributing
#:   them is the same act as redistributing tiktoken's data files.
#: * ``Glm5``/``Qwen3``/``KimiK2``/``DeepSeekV3`` are NOT identical to any
#:   published tiktoken vocabulary; they were extracted from oh-my-pi's native
#:   addon, a third-party vendored artifact. Their licence is unstated, and the
#:   project owner has decided to ship them anyway -- real token counting is the
#:   priority. See the top-level ``NOTICE``.
#:
#: If cleaner provenance matters later, the four vendor tables could be sourced
#: from each vendor's own published ``tokenizer.json`` instead of from the
#: addon -- the UTOK1 container is plain (rank == index, raw token bytes), so
#: dropping such a vocabulary straight in needs no format work.
_PROVENANCE: dict[str, dict[str, str]] = {
    "O200kBase": {"source": "tiktoken o200k_base (byte-identical)", "license": "MIT (upstream OpenAI)"},
    "Cl100kBase": {"source": "tiktoken cl100k_base (byte-identical)", "license": "MIT (upstream OpenAI)"},
    "Glm5": {
        "source": "oh-my-pi native addon (UTOK1 blob)",
        "license": "vendor vocabulary, redistributed with the project owner's acceptance (see NOTICE)",
    },
    "Qwen3": {
        "source": "oh-my-pi native addon (UTOK1 blob)",
        "license": "vendor vocabulary, redistributed with the project owner's acceptance (see NOTICE)",
    },
    "KimiK2": {
        "source": "oh-my-pi native addon (UTOK1 blob)",
        "license": "vendor vocabulary, redistributed with the project owner's acceptance (see NOTICE)",
    },
    "DeepSeekV3": {
        "source": "oh-my-pi native addon (UTOK1 blob)",
        "license": "vendor vocabulary, redistributed with the project owner's acceptance (see NOTICE)",
    },
}

#: The Claude containers. Their contents are Sander Land's measured ctok
#: vocabulary (MIT), vendored by oh-my-pi and shipped here for exact counts, so
#: this is the cleanest provenance of any table in this directory: MIT upstream,
#: with oh-my-pi's own MIT licence on the container spelling.
_CTOK_PROVENANCE: dict[str, dict[str, str]] = {
    "ClaudeV3": {
        "source": "CTOK\\x02 blob from the oh-my-pi addon; vocabulary is sanderland/ctok v1.0.0 (MIT, rev df3b59b)",
        "license": "MIT (sanderland/ctok, https://github.com/sanderland/ctok, via oh-my-pi)",
    },
    "ClaudeV47": {
        "source": "CTOK\\x02 blob from the oh-my-pi addon; vocabulary is sanderland/ctok v1.0.0 (MIT, rev df3b59b)",
        "license": "MIT (sanderland/ctok, https://github.com/sanderland/ctok, via oh-my-pi)",
    },
}

#: CTOK blob fingerprint (vocabulary entry count, from the header's u32 at
#: 0x0A) -> the encodings it serves. ``ClaudeV5``/``ClaudeV5Sonnet`` reuse the
#: v4.7 vocabulary with a different message frame, so they ship no extra data.
_CTOK_ENCODINGS: dict[str, tuple[str, ...]] = {
    "ClaudeV3": ("ClaudeV3",),
    "ClaudeV47": ("ClaudeV47", "ClaudeV5", "ClaudeV5Sonnet"),
}

_CTOK_MAGIC = b"CTOK\x02"

#: CTOK generation -> shipped file name; ``claude_tokenizer`` reads these names.
_CTOK_FILE: dict[str, str] = {"ClaudeV3": "ctok_v3.bin.bz2", "ClaudeV47": "ctok_v4_7.bin.bz2"}

#: CTOK layout, in the manifest's terms. Verified to consume the blob exactly.
_CTOK_CONTAINER = (
    "CTOK\\x02: magic(5) + u8 + u8x2 + u16 LE byte-prefix count + u32 LE vocabulary count; "
    "then <count2> x [u8 n][n bytes] byte-prefix table (the OOV byte floor); then <count> x "
    "[u8 shared][u8 suffix_len][suffix] front-coded, bytewise-sorted tiling vocabulary "
    "(markers spelled 01/02/04/05)"
)


def _read_varint(buf: bytes, i: int) -> tuple[int, int]:
    shift = 0
    value = 0
    while True:
        byte = buf[i]
        i += 1
        value |= (byte & 0x7F) << shift
        if not byte & 0x80:
            break
        shift += 7
    return value, i


def _parse_utok1(buf: bytes) -> list[bytes]:
    if buf[:6] != _UTOK1_MAGIC:
        raise ValueError(f"not a UTOK1 container: {buf[:6]!r}")
    i = 6
    count = int.from_bytes(buf[i : i + 4], "little")
    i += 4
    tokens: list[bytes] = []
    for _ in range(count):
        length, i = _read_varint(buf, i)
        tokens.append(buf[i : i + length])
        i += length
    if i != len(buf):
        raise ValueError(f"UTOK1 container has {len(buf) - i} trailing bytes")
    return tokens


def _iter_utok1_blobs(addon: Path):
    """Yield every decompressed UTOK1 frame embedded in the addon."""
    data = addon.read_bytes()
    import zstandard  # dev-only dependency, provided by the ``dev`` extra

    for match in re.finditer(re.escape(_ZSTD_MAGIC), data):
        offset = match.start()
        frame_header = data[offset + 4]
        if frame_header & 0x18:  # single-segment / checksum flags: no frame content size
            continue
        fcs_len = 1 if (frame_header >> 6) == 0 else (2 if (frame_header >> 6) == 1 else 4)
        declared = int.from_bytes(data[offset + 5 : offset + 5 + fcs_len], "little")
        try:
            out = zstandard.ZstdDecompressor().decompress(data[offset : offset + declared + 64], max_output_size=max(declared, 1))
        except zstandard.ZstdError:
            continue
        if out.startswith(_UTOK1_MAGIC):
            yield out


def _iter_ctok_blobs(addon: Path):
    """Yield every decompressed ``CTOK\\x02`` frame embedded in the addon."""
    data = addon.read_bytes()
    import zstandard  # dev-only dependency, provided by the ``dev`` extra

    for match in re.finditer(re.escape(_ZSTD_MAGIC), data):
        offset = match.start()
        frame_header = data[offset + 4]
        if frame_header & 0x18:  # single-segment / checksum flags: no frame content size
            continue
        fcs_len = 1 if (frame_header >> 6) == 0 else (2 if (frame_header >> 6) == 1 else 4)
        declared = int.from_bytes(data[offset + 5 : offset + 5 + fcs_len], "little")
        try:
            out = zstandard.ZstdDecompressor().decompress(data[offset : offset + declared + 64], max_output_size=max(declared, 1))
        except zstandard.ZstdError:
            continue
        if out.startswith(_CTOK_MAGIC):
            yield out


def extract_claude_vocabs(addon: Path, manifest: dict[str, object]) -> None:
    """Write one bz2'd CTOK container per Claude encoding into ``manifest``.

    The container is shipped verbatim: :mod:`voidcode.provider.claude_tokenizer`
    decodes it at load time, the same bytes the engine parses.
    """
    for blob in _iter_ctok_blobs(addon):
        size = len(blob)
        if size not in (202428, 57304):  # the two known generations
            print(f"  skipped CTOK blob of {size} bytes (unknown size)")
            continue
        count = int.from_bytes(blob[0x0A:0x0E], "little")
        name = "ClaudeV3" if size == 202428 else "ClaudeV47"
        payload = bz2.compress(blob, compresslevel=9)
        (DATA_DIR / f"{_CTOK_FILE[name]}").write_bytes(payload)
        for encoding in _CTOK_ENCODINGS[name]:
            manifest[encoding] = {
                "tokens": count,
                "raw_bytes": size,
                "shipped_bytes": len(payload),
                "container": _CTOK_CONTAINER,
                **_CTOK_PROVENANCE[name],
            }
        print(f"  {name:<12} tokens={count:>7} raw={size:>9} bz2={len(payload):>9}")


def _default_addon() -> Path:
    candidates = sorted(Path.home().glob(".omp/natives/*/pi_natives.linux-x64-modern.node"))
    if not candidates:
        raise SystemExit("no omp native addon found under ~/.omp/natives/*/; pass --addon")
    return candidates[-1]


def _default_models_db() -> Path:
    path = Path.home() / ".omp" / "agent" / "models.db"
    if not path.exists():
        raise SystemExit(f"omp routing table not found at {path}; pass --models-db")
    return path


def extract_vocabs(addon: Path) -> dict[str, int]:
    """Write one bz2'd UTOK1 container per encoding; return name -> raw bytes."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    written: dict[str, int] = {}
    manifest: dict[str, object] = {}
    for blob in _iter_utok1_blobs(addon):
        tokens = _parse_utok1(blob)
        name = _ENC_BY_TOKEN_COUNT.get(len(tokens))
        if name is None:
            print(f"  skipped UTOK1 blob with {len(tokens)} tokens (unknown fingerprint)")
            continue
        payload = bz2.compress(blob, compresslevel=9)
        (DATA_DIR / f"{name}.utok1.bz2").write_bytes(payload)
        written[name] = len(blob)
        manifest[name] = {
            "tokens": len(tokens),
            "raw_bytes": len(blob),
            "shipped_bytes": len(payload),
            "container": "UTOK1: magic + u32 LE count + N x (ULEB128 length + raw token bytes); rank == index",
            **_PROVENANCE[name],
        }
        print(f"  {name:<12} tokens={len(tokens):>7} raw={len(blob):>9} bz2={len(payload):>9}")
    missing = set(_ENC_BY_TOKEN_COUNT.values()) - set(written)
    if missing:
        raise SystemExit(f"addon did not yield these encodings: {sorted(missing)}")
    extract_claude_vocabs(addon, manifest)
    (DATA_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return written


def extract_routing(models_db: Path) -> dict[str, dict[str, str]]:
    """Read omp's model -> tokenizer routing table, keyed by provider then model."""
    routing: dict[str, dict[str, str]] = {}
    with sqlite3.connect(models_db) as connection:
        rows = connection.execute("select provider_id, models from model_cache").fetchall()
    for provider_id, models_json in rows:
        data = json.loads(models_json)
        items = data.items() if isinstance(data, dict) else ((m.get("id"), m) for m in data)
        for model_id, model in items:
            if not isinstance(model, dict) or not isinstance(model_id, str):
                continue
            name = model.get("tokenizer")
            if isinstance(name, str) and name:
                routing.setdefault(provider_id, {})[model_id.strip().lower()] = name
    return {provider: models for provider, models in sorted(routing.items()) if models}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--addon", type=Path, default=None, help="path to pi_natives.*.node")
    parser.add_argument("--models-db", type=Path, default=None, help="path to ~/.omp/agent/models.db")
    args = parser.parse_args()

    addon = args.addon or _default_addon()
    print(f"addon: {addon}")
    print("vocabularies:")
    sizes = extract_vocabs(addon)
    print(f"  total shipped: {sum((DATA_DIR / f'{n}.utok1.bz2').stat().st_size for n in sizes):,} bytes")

    models_db = args.models_db or _default_models_db()
    routing = extract_routing(models_db)
    ROUTING_PATH.write_text(json.dumps(routing, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"routing: {sum(len(m) for m in routing.values())} tagged models across {len(routing)} providers")
    return 0


if __name__ == "__main__":
    sys.exit(main())
