"""Generate the frontend's backend-facing types from the transport's OpenAPI document.

Dev-time generator only; never imported by the runtime.

The input is the document the transport itself serves at ``GET
/api/openapi.json``: this script builds ``RuntimeTransportApp`` in-process and
drives that exact route through its ASGI interface, so the generator consumes the
same bytes a client would. There is no hand-maintained copy of the schema, no
server process, no port and no network. The served bytes are already the
transport's byte-stable rendering (sorted keys, one JSON renderer per response),
and ``openapi-typescript`` is pinned by ``frontend/bun.lock``, so regenerating on
a clean checkout reproduces the committed file byte for byte. Which schema the
document carries comes from ``src/voidcode/runtime/transport/http_models.py``;
``tests/integration/test_http_response_schema.py`` pins those models to the
bodies the handlers really write.

Two routes cannot be expressed as a JSON response body: the SSE streams of
``POST /api/runtime/run/stream`` and ``GET /api/sessions/{id}/events``. OpenAPI
has no event-stream body, so those routes publish their frame model as
``content[text/event-stream].itemSchema`` and the document registers the model
under ``components.schemas`` like every other body. Both properties are asserted
here, because a generator that silently dropped them would emit a frontend
stream type that nothing pins.

Usage::

    mise run frontend:api:generate     # rewrite frontend/src/lib/runtime/generated/api.d.ts
    mise run frontend:api:check        # fail when the committed file is stale
"""

from __future__ import annotations

import argparse
import asyncio
import json
import subprocess
import sys
import tempfile
from collections.abc import Iterator
from pathlib import Path
from typing import Any, cast

REPO_ROOT = Path(__file__).resolve().parent.parent
FRONTEND_ROOT = REPO_ROOT / "frontend"
OUTPUT_PATH = FRONTEND_ROOT / "src" / "lib" / "runtime" / "generated" / "api.d.ts"
GENERATOR_BINARY = FRONTEND_ROOT / "node_modules" / ".bin" / "openapi-typescript"

OPENAPI_ROUTE = "/api/openapi.json"

#: Route template -> the frame model its stream publishes, for the two SSE
#: routes. OpenAPI cannot describe an event-stream body, so this is the only
#: place the frame contract appears in the document.
_STREAM_FRAMES: dict[tuple[str, str], str] = {
    ("post", "/api/runtime/run/stream"): "RunStreamFrameBody",
    ("get", "/api/sessions/{session_id}/events"): "SessionEventFrameBody",
}

_HEADER = """\
/**
 * @generated by scripts/generate_frontend_api_types.py - DO NOT EDIT.
 *
 * Backend wire types for the runtime HTTP transport, generated from the
 * document the transport serves at `GET /api/openapi.json` (the models behind
 * it live in `src/voidcode/runtime/transport/http_models.py`).
 *
 * These are compile-time types only. Nothing here validates a response at
 * runtime, and no runtime check may be derived from them: the transport's
 * bodies are pinned by `tests/integration/test_http_response_schema.py`, not by
 * the browser. Hand-written refinements and the frontend-owned types that the
 * backend does not describe live in `../types.ts`, which re-exports these under
 * the names the app uses.
 *
 * Regenerate with `mise run frontend:api:generate`. `mise run frontend:api:check`
 * fails when this file no longer matches the backend schema.
 */
"""


def _openapi_document() -> dict[str, Any]:
    """Fetch the served OpenAPI document in-process, without a server or a port.

    ``RuntimeTransportApp`` is built with a runtime factory that is never called:
    the document route reads the registered routes and their models, and never
    takes a runtime lease.
    """

    def _no_runtime() -> Any:
        raise RuntimeError("the OpenAPI document must not need a runtime instance")

    transport = _import_transport()
    app = transport.RuntimeTransportApp(runtime_factory=_no_runtime)

    sent: list[dict[str, Any]] = []
    request_sent = False

    async def _receive() -> dict[str, Any]:
        nonlocal request_sent
        if not request_sent:
            request_sent = True
            return {"type": "http.request", "body": b"", "more_body": False}
        return {"type": "http.disconnect"}

    async def _send(message: dict[str, Any]) -> None:
        sent.append(message)

    scope = {
        "type": "http",
        "method": "GET",
        "path": OPENAPI_ROUTE,
        "raw_path": OPENAPI_ROUTE.encode("utf-8"),
        "query_string": b"",
        "headers": [],
    }
    # Boundary: the ASGI app callable and its message dicts are untyped; this
    # drives the served document in-process rather than through a socket.
    asyncio.run(cast(Any, app)(scope, _receive, _send))

    start = next(message for message in sent if message["type"] == "http.response.start")
    status = cast(int, start["status"])
    body = b"".join(cast(bytes, message.get("body", b"")) for message in sent if message["type"] == "http.response.body")
    if status != 200:
        raise SystemExit(f"{OPENAPI_ROUTE} answered {status}, expected 200: {body[:400]!r}")

    # Boundary: JSON decode of the served OpenAPI document.
    document = cast(dict[str, Any], json.loads(body))
    _assert_stream_frames_published(document)
    return document


def _import_transport() -> Any:
    """Import the transport module, failing with a usable message when it is missing."""
    try:
        from voidcode.runtime.transport import http as transport_http
    except ImportError as exc:  # pragma: no cover - environment failure
        raise SystemExit(f"cannot import the runtime transport (run `uv sync --extra dev` first): {exc}") from exc
    return transport_http


def _assert_stream_frames_published(document: dict[str, Any]) -> None:
    """Fail loudly when a stream route no longer publishes its frame model.

    The frontend's stream chunk type is derived from ``components.schemas``, so a
    stream route that stopped declaring a frame — or a document that stopped
    registering it — has to stop generation here instead of silently emitting a
    worse type.
    """
    # Boundary: the decoded document is untyped JSON; these casts pin the
    # nested shapes the generator traverses.
    schemas = cast(dict[str, Any], document.get("components", {}).get("schemas", {}))
    for (method, path), frame in _STREAM_FRAMES.items():
        operation = cast(dict[str, Any], document.get("paths", {}).get(path, {})).get(method)
        if operation is None:
            raise SystemExit(f"the document no longer describes {method.upper()} {path}")
        content = cast(dict[str, Any], operation.get("responses", {})).get("200", {}).get("content", {})
        item_schema = cast(dict[str, Any], content.get("text/event-stream", {})).get("itemSchema")
        if item_schema != {"$ref": f"#/components/schemas/{frame}"}:
            raise SystemExit(f"{method.upper()} {path} does not publish its {frame} frame: {item_schema!r}")
        if frame not in schemas:
            raise SystemExit(f"the document registers no {frame} schema for {method.upper()} {path}")


def _run_openapi_typescript(document: dict[str, Any]) -> str:
    """Run the pinned generator over the document and return the emitted TypeScript."""
    if not GENERATOR_BINARY.is_file():
        raise SystemExit(f"missing {GENERATOR_BINARY}; run `bun install` in frontend/ first")

    with tempfile.TemporaryDirectory(prefix="voidcode-openapi-") as directory:
        document_path = Path(directory) / "openapi.json"
        output_path = Path(directory) / "api.d.ts"
        # The same rendering the transport serves: sorted keys, escaped non-ASCII.
        document_path.write_text(json.dumps(document, sort_keys=True), encoding="utf-8")
        completed = subprocess.run(
            [str(GENERATOR_BINARY), str(document_path), "--output", str(output_path)],
            cwd=FRONTEND_ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        if completed.returncode != 0:
            raise SystemExit(f"openapi-typescript failed ({completed.returncode}):\n{completed.stderr}")
        if not output_path.is_file():
            raise SystemExit("openapi-typescript wrote no output file")
        return output_path.read_text(encoding="utf-8")


def _generated_text() -> str:
    """The full committed file: our header followed by the generator's own."""
    return _HEADER + _run_openapi_typescript(_openapi_document())


def _render_diff(expected: str, actual: str) -> Iterator[str]:
    expected_lines = expected.splitlines()
    actual_lines = actual.splitlines()
    for index, (expected_line, actual_line) in enumerate(zip(expected_lines, actual_lines, strict=False), start=1):
        if expected_line != actual_line:
            yield f"  first difference at line {index}:"
            yield f"    backend schema: {expected_line.strip()!r}"
            yield f"    committed file: {actual_line.strip()!r}"
            return
    yield f"  the committed file has {len(actual_lines)} lines, the backend schema needs {len(expected_lines)}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed file matches the backend schema instead of rewriting it",
    )
    arguments = parser.parse_args()

    generated = _generated_text()
    if arguments.check:
        if not OUTPUT_PATH.is_file():
            raise SystemExit(f"{OUTPUT_PATH} is missing; run `mise run frontend:api:generate`")
        committed = OUTPUT_PATH.read_text(encoding="utf-8")
        if committed == generated:
            print(f"generated API types are up to date: {OUTPUT_PATH.relative_to(REPO_ROOT)}")
            return 0
        print(f"generated API types are stale: {OUTPUT_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
        for line in _render_diff(generated, committed):
            print(line, file=sys.stderr)
        print("run `mise run frontend:api:generate` and commit the result", file=sys.stderr)
        return 1

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    # Written through a sibling temp file so an interrupted run never truncates
    # the committed artifact.
    temporary = OUTPUT_PATH.with_name(f"{OUTPUT_PATH.name}.tmp")
    temporary.write_text(generated, encoding="utf-8")
    temporary.replace(OUTPUT_PATH)
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({len(generated)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
